export default {
  GET_ITEMS_REQUEST: "GET_ITEMS_REQUEST",
  GET_ITEMS_SUCCESS: "GET_ITEMS_SUCCESS",
  GET_ITEMS_FAILED: "GET_ITEMS_FAILED",

  PAY_ORDER_REQUEST: "PAY_ORDER_REQUEST",
  PAY_ORDER_SUCCESS: "PAY_ORDER_SUCCESS",
  // CHECKOUT_ORDER_FAILD: "CHECKOUT_ORDER_FAILD",
  POST_ORDER_REQUEST: "POST_ORDER_REQUEST",
  POST_ORDER_SUCCESS: "POST_ORDER_SUCCESS",
  POST_ORDER_FAILED: "POST_ORDER_FAILED",

  POST_ITEMS_REQUEST: "POST_ITEMS_REQUEST",
  POST_ITEMS_SUCCESS: "POST_ITEMS_SUCCESS",
  POST_ITEMS_FAILED: "POST_ITEMS_FAILED",

  GET_USER_REQUEST: "GET_USER_REQUEST",
  GET_USER_SUCCESS: "GET_USER_SUCCESS",
  GET_USER_FAILED: "GET_USER_FAILED",

  BUYER_REGISTER_REQUEST: "BUYER_REGISTER_REQUEST",
  BUYER_REGISTER_SUCCESS: "BUYER_REGISTER_SUCCESS",
  BUYER_REGISTER_FAILED: "BUYER_REGISTER_FAILED",
  SELLER_REGISTER_REQUEST: "SELLER_REGISTER_REQUEST",
  SELLER_REGISTER_SUCCESS: "SELLER_REGISTER_SUCCESS",
  SELLER_REGISTER_FAILED: "SELLER_REGISTER_FAILED",

  BUYER_SIGNIN_REQUEST: "BUYER_SIGNIN_REQUEST",
  BUYER_SIGNIN_SUCCESS: "BUYER_SIGNIN_SUCCESS",
  BUYER_SIGNIN_FAILED: "BUYER_SIGNIN_FAILED",
  SELLER_SIGNIN_REQUEST: "SELLER_SIGNIN_REQUEST",
  SELLER_SIGNIN_SUCCESS: "SELLER_SIGNIN_SUCCESS",
  SELLER_SIGNIN_FAILED: "SELLER_SIGNIN_FAILED",

  GET_ITEM_REQUEST: "GET_ITEM_REQUEST",
  GET_ITEM_SUCCESS: "GET_ITEM_SUCCESS",
  GET_ITEM_FAILED: "GET_ITEM_FAILED",

  GET_ALLFRUIT_REQUEST: "GET_ALLFRUIT_REQUEST",
  GET_ALLFRUIT_SUCCESS: "GET_ALLFRUIT_SUCCESS",
  GET_ALLFRUIT_FAILED: "GET_ALLFRUIT_FAILED",

  GET_ALLVEGETABLE_REQUEST: "GET_ALLVEGETABLE_REQUEST",
  GET_ALLVEGETABLE_SUCCESS: "GET_ALLVEGETABLE_SUCCESS",
  GET_ALLVEGETABLE_FAILED: "GET_ALLVEGETABLE_FAILED",
};
