export default {

  GET_ITEMS_REQUEST: "GET_ITEMS_REQUEST",
  GET_ITEMS_SUCCESS: "GET_ITEMS_SUCCESS",
  GET_ITEMS_FAILED: "GET_ITEMS_FAILED",

  GET_USER_REQUEST: "GET_USER_REQUEST",
  GET_USER_SUCCESS: "GET_USER_SUCCESS",
  GET_USER_FAILED: "GET_USER_FAILED",

  

};
